Add CycleOps Fluid2 power calculator
dhague/vpower pull request #8
Opened 2018-09-13 11:57 UTC by oldnapalm

2018-09-13 20:17 UTC, oldnapalm commented
Sorry, I made some changes later that should not be in the pull request, my intention was to pull only commits a1d4aa4 and 20d2102

2018-09-16 17:12 UTC, dhague requested changes

2018-09-16 17:12 UTC, dhague commented on CycleOpsFluid2PowerCalculator2.py
> +from AbstractPowerCalculator import AbstractPowerCalculator
This file, ending in "2", seems to be surplus to requirements

2018-09-16 22:20 UTC, oldnapalm commented on CycleOpsFluid2PowerCalculator2.py
> +from AbstractPowerCalculator import AbstractPowerCalculator
Yes, that file is not needed, it's another power curve, I put it into my fork just to store it. My intention was to pull only commits a1d4aa4 and 20d2102, I didn't know changes I made later were going to be added do pull request. Can you select only those commits or do you want me to start over? Sorry, I'm new to github.

2018-09-17 08:16 UTC, dhague commented on CycleOpsFluid2PowerCalculator2.py
> +from AbstractPowerCalculator import AbstractPowerCalculator
Unfortunately I can only approve the entire pull request. Maybe create a new branch at your last commit, and then reset the original branch to the correct commit and push that to the PR branch?

2018-09-17 08:17 UTC, dhague commented on CycleOpsFluid2PowerCalculator2.py
> +from AbstractPowerCalculator import AbstractPowerCalculator
If that's all too complicated, just close this PR, create a new branch at the correct commit, and push that as a new PR.

2018-09-17 11:11 UTC, closed without merging